name: Tareas Diarias Symfony

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  symfony-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Instalar Dependencias (Composer)
        working-directory: ./club-cine
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Ejecutar Script Directo
        working-directory: ./club-cine
        env:
          APP_ENV: prod
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Symfony NECESITA que estas existan para que el Kernel haga el 'boot'
          # Si no las tienes en Secrets, pon un valor cualquiera para "engañar" al Kernel
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY || 'dummy_key' }}
          MAILER_DSN: ${{ secrets.MAILER_DSN || 'null://localhost' }}
        # Ejecutamos tu archivo PHP directamente
        run: php scripts/daily_tasks.php
