name: Tareas Diarias Symfony

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  symfony-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Instalar Dependencias (Composer)
        working-directory: ./club-cine
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Ejecutar Script Directo
        working-directory: ./club-cine
        env:
          APP_ENV: prod
          # Aseguramos que siempre haya valores para que el Kernel.boot() no explote
          APP_SECRET: ${{ secrets.APP_SECRET || '3f3e4e5d6c7b8a90123456789abcdef0' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY || 'no_necesaria_aqui' }}
          MAILER_DSN: ${{ secrets.MAILER_DSN || 'null://localhost' }}
        # LA RUTA FINAL SEGÚN TU INDICACIÓN:
        run: php scripts/close-expired
